---
apiVersion: v1
kind: Service
metadata:
    name: ram-service
    labels:
      app: ramnginx
spec:
  selector:
     app: ramnginx
  type: NodePort
  ports:
  - nodePort: 32003
    port: 80
    targetPort: 80

